//go:build !ignore_autogenerated

/*
Copyright 2022 Nine Internet Solutions AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildResourceStatus) DeepCopyInto(out *ChildResourceStatus) {
	*out = *in
	if in.ChildResourceErrors != nil {
		in, out := &in.ChildResourceErrors, &out.ChildResourceErrors
		*out = make([]ChildResourceError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildResourceStatus.
func (in *ChildResourceStatus) DeepCopy() *ChildResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ChildResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DNSVerificationStatusEntries) DeepCopyInto(out *DNSVerificationStatusEntries) {
	{
		in := &in
		*out = make(DNSVerificationStatusEntries, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSVerificationStatusEntries.
func (in DNSVerificationStatusEntries) DeepCopy() DNSVerificationStatusEntries {
	if in == nil {
		return nil
	}
	out := new(DNSVerificationStatusEntries)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSVerificationStatusEntry) DeepCopyInto(out *DNSVerificationStatusEntry) {
	*out = *in
	if in.LatestSuccess != nil {
		in, out := &in.LatestSuccess, &out.LatestSuccess
		*out = (*in).DeepCopy()
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(VerificationError)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSVerificationStatusEntry.
func (in *DNSVerificationStatusEntry) DeepCopy() *DNSVerificationStatusEntry {
	if in == nil {
		return nil
	}
	out := new(DNSVerificationStatusEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenceStatus) DeepCopyInto(out *ReferenceStatus) {
	*out = *in
	if in.ReferenceErrors != nil {
		in, out := &in.ReferenceErrors, &out.ReferenceErrors
		*out = make(ReferenceErrors, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferenceStatus.
func (in *ReferenceStatus) DeepCopy() *ReferenceStatus {
	if in == nil {
		return nil
	}
	out := new(ReferenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScrapeConfig) DeepCopyInto(out *ScrapeConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalMetrics != nil {
		in, out := &in.AdditionalMetrics, &out.AdditionalMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScrapedBy != nil {
		in, out := &in.ScrapedBy, &out.ScrapedBy
		*out = make([]LocalReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScrapeConfig.
func (in *ScrapeConfig) DeepCopy() *ScrapeConfig {
	if in == nil {
		return nil
	}
	out := new(ScrapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationError) DeepCopyInto(out *VerificationError) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationError.
func (in *VerificationError) DeepCopy() *VerificationError {
	if in == nil {
		return nil
	}
	out := new(VerificationError)
	in.DeepCopyInto(out)
	return out
}
