//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Nine Internet Solutions AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1alpha1 "github.com/ninech/apis/meta/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginx) DeepCopyInto(out *IngressNginx) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginx.
func (in *IngressNginx) DeepCopy() *IngressNginx {
	if in == nil {
		return nil
	}
	out := new(IngressNginx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngressNginx) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxCache) DeepCopyInto(out *IngressNginxCache) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxCache.
func (in *IngressNginxCache) DeepCopy() *IngressNginxCache {
	if in == nil {
		return nil
	}
	out := new(IngressNginxCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxCloudflare) DeepCopyInto(out *IngressNginxCloudflare) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxCloudflare.
func (in *IngressNginxCloudflare) DeepCopy() *IngressNginxCloudflare {
	if in == nil {
		return nil
	}
	out := new(IngressNginxCloudflare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxDefaultBackend) DeepCopyInto(out *IngressNginxDefaultBackend) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(metav1alpha1.Image)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxDefaultBackend.
func (in *IngressNginxDefaultBackend) DeepCopy() *IngressNginxDefaultBackend {
	if in == nil {
		return nil
	}
	out := new(IngressNginxDefaultBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxList) DeepCopyInto(out *IngressNginxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IngressNginx, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxList.
func (in *IngressNginxList) DeepCopy() *IngressNginxList {
	if in == nil {
		return nil
	}
	out := new(IngressNginxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngressNginxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxObservation) DeepCopyInto(out *IngressNginxObservation) {
	*out = *in
	in.ChildResourceStatus.DeepCopyInto(&out.ChildResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxObservation.
func (in *IngressNginxObservation) DeepCopy() *IngressNginxObservation {
	if in == nil {
		return nil
	}
	out := new(IngressNginxObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxParameters) DeepCopyInto(out *IngressNginxParameters) {
	*out = *in
	out.Cluster = in.Cluster
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(IngressNginxCache)
		**out = **in
	}
	if in.Cloudflare != nil {
		in, out := &in.Cloudflare, &out.Cloudflare
		*out = new(IngressNginxCloudflare)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultBackend != nil {
		in, out := &in.DefaultBackend, &out.DefaultBackend
		*out = new(IngressNginxDefaultBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.IPSharing != nil {
		in, out := &in.IPSharing, &out.IPSharing
		*out = new(metav1alpha1.Reference)
		**out = **in
	}
	if in.ScrapeConfigurations != nil {
		in, out := &in.ScrapeConfigurations, &out.ScrapeConfigurations
		*out = make([]metav1alpha1.ScrapeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxParameters.
func (in *IngressNginxParameters) DeepCopy() *IngressNginxParameters {
	if in == nil {
		return nil
	}
	out := new(IngressNginxParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxSpec) DeepCopyInto(out *IngressNginxSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxSpec.
func (in *IngressNginxSpec) DeepCopy() *IngressNginxSpec {
	if in == nil {
		return nil
	}
	out := new(IngressNginxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressNginxStatus) DeepCopyInto(out *IngressNginxStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressNginxStatus.
func (in *IngressNginxStatus) DeepCopy() *IngressNginxStatus {
	if in == nil {
		return nil
	}
	out := new(IngressNginxStatus)
	in.DeepCopyInto(out)
	return out
}
