on:
  push:
    branches:
      - main
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  # this is a bit convoluted but the build and deploy steps had to be
  # separated as the actions/upload-pages-artifact requires GNU tar to be
  # present which is not there in the redocusaurus container.
  build:
    runs-on: ubuntu-latest
    container: node:lts-alpine3.17
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Redoc build
        working-directory: ./docs
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: redocusaurus
          path: docs/build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: redocusaurus
          path: public/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1